In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [62]:
orthologs = pd.read_csv('/cndd/Public_Datasets/single_cell_methylome/summary_files/orthologs.txt',
                        sep='\t')

In [3]:
evals = pd.read_csv('/cndd2/ethan/projects/enh_gene_linkage/intergenic_corr/data/evals_w_fdr_100kb_12k_genes.tsv', sep='\t')

In [4]:
evals.head()

,Unnamed: 0,gene,ens,in_gene,val,val2,val_clustershuffled,val2_clustershuffled,dist,pvalues,...,fdr<100kb shuffled (cluster label),pvalues2,fdr2<100kb,fdr2<200kb,fdr2<500kb,fdr2<100kb shuffled (cluster label),fdr_mcg,fdr_mcg_corr,fdr_atac,fdr_atac_corr
0,94,ENSMUSG00000000001,147662,False,-0.039720,0.044097,-0.265784,-0.136448,92177,0.424733,...,1.095838,0.450781,0.744850,0.797258,0.876520,1.032819,0.726151,0.662643,0.744850,0.721180
1,95,ENSMUSG00000000001,147663,False,0.024620,0.051756,-0.380239,-0.101215,91955,0.499490,...,0.922071,0.439489,0.738874,0.792315,0.873352,1.051270,0.770029,0.835107,0.738874,0.702838
2,96,ENSMUSG00000000001,147664,False,-0.022212,0.074516,-0.081081,-0.112376,84155,0.445065,...,1.037449,0.406090,0.720486,0.776735,0.862787,1.112977,0.738378,0.711723,0.720486,0.647348
3,97,ENSMUSG00000000001,147665,False,-0.147171,0.017398,0.194660,-0.279352,76112,0.306660,...,1.762511,0.490344,0.765055,0.813756,0.886827,0.979848,0.648328,0.367841,0.765055,0.780787
4,98,ENSMUSG00000000001,147666,False,0.122880,0.122005,0.050224,0.120910,63221,0.611919,...,0.806321,0.338683,0.679892,0.742359,0.840268,1.285390,0.829016,1.028145,0.679892,0.528936

In [5]:
atac_genes = evals.loc[evals.fdr_atac_corr < .05].gene.unique()
mcg_genes = evals.loc[evals.fdr_mcg_corr < .05].gene.unique()

In [6]:
len(atac_genes)

8071

In [7]:
len(mcg_genes)

10732

In [8]:
possible_genes = np.union1d(atac_genes, mcg_genes)

In [9]:
len(possible_genes)

11014

In [10]:
orthologs.head()

,GeneType,hsa_gID,hsa_tID,hsa_pID,hsa_gName,hsa_tName,mmu_gID,mmu_tID,mmu_pID,mmu_gName,mmu_tName,HumanPercId,MousePercId
0,protein,ENSG00000136928,ENST00000259455,ENSP00000259455,GABBR2,GABBR2-001,ENSMUSG00000039809,ENSMUST00000107749,ENSMUSP00000103378,Gabbr2,Gabbr2-001,97.0,97.0
1,protein,ENSG00000140931,ENST00000424011,ENSP00000400482,CMTM3,CMTM3-001,ENSMUSG00000031875,ENSMUST00000034343,ENSMUSP00000034343,Cmtm3,Cmtm3-201,88.0,88.0
2,protein,ENSG00000123472,ENST00000371937,ENSP00000361005,ATPAF1,ATPAF1-001,NaN,NaN,ENSMUSP00000030478,NaN,Atpaf1-001,89.0,89.0
3,protein,ENSG00000125780,ENST00000381458,ENSP00000370867,TGM3,TGM3-001,ENSMUSG00000027401,ENSMUST00000110299,ENSMUSP00000105928,Tgm3,Tgm3-001,76.0,76.0
4,protein,ENSG00000224531,ENST00000416247,ENSP00000451866,SMIM13,C6orf228-002,ENSMUSG00000091264,ENSMUST00000165561,ENSMUSP00000130956,Smim13,BC024659-001,88.0,88.0

In [11]:
orthologs = orthologs.loc[orthologs.mmu_gID.isin(possible_genes)]

In [12]:
orthologs.shape

(9054, 13)

In [13]:
orthologs.head()

,GeneType,hsa_gID,hsa_tID,hsa_pID,hsa_gName,hsa_tName,mmu_gID,mmu_tID,mmu_pID,mmu_gName,mmu_tName,HumanPercId,MousePercId
0,protein,ENSG00000136928,ENST00000259455,ENSP00000259455,GABBR2,GABBR2-001,ENSMUSG00000039809,ENSMUST00000107749,ENSMUSP00000103378,Gabbr2,Gabbr2-001,97.0,97.0
4,protein,ENSG00000224531,ENST00000416247,ENSP00000451866,SMIM13,C6orf228-002,ENSMUSG00000091264,ENSMUST00000165561,ENSMUSP00000130956,Smim13,BC024659-001,88.0,88.0
8,protein,ENSG00000161981,ENST00000383018,ENSP00000372482,SNRNP25,SNRNP25-201,ENSMUSG00000040767,ENSMUST00000039601,ENSMUSP00000046654,Snrnp25,Snrnp25-001,98.0,98.0
11,protein,ENSG00000125741,ENST00000323060,ENSP00000319817,OPA3,OPA3-202,ENSMUSG00000052214,ENSMUST00000063976,ENSMUSP00000069965,Opa3,Opa3-001,76.0,76.0
12,protein,ENSG00000204104,ENST00000373327,ENSP00000362424,TRAF3IP1,TRAF3IP1-001,ENSMUSG00000034292,ENSMUST00000047242,ENSMUSP00000042391,Traf3ip1,Traf3ip1-201,70.0,70.0

In [14]:
np.sum(orthologs.MousePercId > 75)

8040

In [15]:
orthologs = orthologs.loc[orthologs.MousePercId > 75]

# get human genes

In [16]:
hg38 = pd.read_csv('/cndd/junhao/genomes/hg38/gencode.v25.annotation.gtf',
                   skiprows = 5, sep='\t', header=None)

In [17]:
hg38.head()

,0,1,2,3,4,5,6,7,8
0,chr1,HAVANA,gene,11869,14409,.,+,.,"gene_id ""ENSG00000223972.5""; gene_type ""transc..."
1,chr1,HAVANA,transcript,11869,14409,.,+,.,"gene_id ""ENSG00000223972.5""; transcript_id ""EN..."
2,chr1,HAVANA,exon,11869,12227,.,+,.,"gene_id ""ENSG00000223972.5""; transcript_id ""EN..."
3,chr1,HAVANA,exon,12613,12721,.,+,.,"gene_id ""ENSG00000223972.5""; transcript_id ""EN..."
4,chr1,HAVANA,exon,13221,14409,.,+,.,"gene_id ""ENSG00000223972.5""; transcript_id ""EN..."

In [18]:
hg38 = hg38.loc[hg38[2] == 'gene']

In [19]:
hg38.head()

,0,1,2,3,4,5,6,7,8
0,chr1,HAVANA,gene,11869,14409,.,+,.,"gene_id ""ENSG00000223972.5""; gene_type ""transc..."
12,chr1,HAVANA,gene,14404,29570,.,-,.,"gene_id ""ENSG00000227232.5""; gene_type ""unproc..."
25,chr1,ENSEMBL,gene,17369,17436,.,-,.,"gene_id ""ENSG00000278267.1""; gene_type ""miRNA""..."
28,chr1,HAVANA,gene,29554,31109,.,+,.,"gene_id ""ENSG00000243485.4""; gene_type ""lincRN..."
38,chr1,HAVANA,gene,34554,36081,.,-,.,"gene_id ""ENSG00000237613.2""; gene_type ""lincRN..."

In [29]:
hg38 = hg38.drop(8, axis=1)

In [30]:
hg38.to_csv('hg38_gtf_cleaned', index=None, columns=None, sep='\t')

In [34]:
hg38.head()

,0,1,2,3,4,5,6,7,gene_id,gene_type,gene_status,gene_name
0,chr1,HAVANA,gene,11869,14409,.,+,.,ENSG00000223972,"""transcribed_unprocessed_pseudogene""","""KNOWN""","""DDX11L1"""
12,chr1,HAVANA,gene,14404,29570,.,-,.,ENSG00000227232,"""unprocessed_pseudogene""","""KNOWN""","""WASH7P"""
25,chr1,ENSEMBL,gene,17369,17436,.,-,.,ENSG00000278267,"""miRNA""","""KNOWN""","""MIR6859-1"""
28,chr1,HAVANA,gene,29554,31109,.,+,.,ENSG00000243485,"""lincRNA""","""KNOWN""","""MIR1302-2"""
38,chr1,HAVANA,gene,34554,36081,.,-,.,ENSG00000237613,"""lincRNA""","""KNOWN""","""FAM138A"""

In [33]:
hg38['gene_id'] = [i.strip('"') for i in hg38['gene_id']]
hg38['gene_id'] = [i.split('.')[0] for i in hg38['gene_id']]

In [35]:
orthologs.head()

,GeneType,hsa_gID,hsa_tID,hsa_pID,hsa_gName,hsa_tName,mmu_gID,mmu_tID,mmu_pID,mmu_gName,mmu_tName,HumanPercId,MousePercId
0,protein,ENSG00000136928,ENST00000259455,ENSP00000259455,GABBR2,GABBR2-001,ENSMUSG00000039809,ENSMUST00000107749,ENSMUSP00000103378,Gabbr2,Gabbr2-001,97.0,97.0
4,protein,ENSG00000224531,ENST00000416247,ENSP00000451866,SMIM13,C6orf228-002,ENSMUSG00000091264,ENSMUST00000165561,ENSMUSP00000130956,Smim13,BC024659-001,88.0,88.0
8,protein,ENSG00000161981,ENST00000383018,ENSP00000372482,SNRNP25,SNRNP25-201,ENSMUSG00000040767,ENSMUST00000039601,ENSMUSP00000046654,Snrnp25,Snrnp25-001,98.0,98.0
11,protein,ENSG00000125741,ENST00000323060,ENSP00000319817,OPA3,OPA3-202,ENSMUSG00000052214,ENSMUST00000063976,ENSMUSP00000069965,Opa3,Opa3-001,76.0,76.0
14,protein,ENSG00000015592,ENST00000350889,ENSP00000342538,STMN4,STMN4-001,ENSMUSG00000022044,ENSMUST00000074523,ENSMUSP00000074113,Stmn4,Stmn4-001,87.0,87.0

In [63]:
orthologs.loc[orthologs.mmu_gName == "Stim2"]

Empty DataFrame
Columns: [GeneType, hsa_gID, hsa_tID, hsa_pID, hsa_gName, hsa_tName, mmu_gID, mmu_tID, mmu_pID, mmu_gName, mmu_tName, HumanPercId, MousePercId]
Index: []

In [36]:
use_genes = hg38.loc[hg38.gene_id.isin(orthologs['hsa_gID'])]

In [37]:
use_genes.shape

(7763, 12)

In [38]:
orthologs.shape

(8040, 13)

In [39]:
use_genes.head()

,0,1,2,3,4,5,6,7,gene_id,gene_type,gene_status,gene_name
1465,chr1,HAVANA,gene,1020123,1056118,.,+,.,ENSG00000188157,"""protein_coding""","""KNOWN""","""AGRN"""
2396,chr1,HAVANA,gene,1253909,1273885,.,-,.,ENSG00000160087,"""protein_coding""","""KNOWN""","""UBE2J2"""
2936,chr1,HAVANA,gene,1292376,1309609,.,-,.,ENSG00000131584,"""protein_coding""","""KNOWN""","""ACAP3"""
3193,chr1,HAVANA,gene,1311585,1324691,.,-,.,ENSG00000127054,"""protein_coding""","""KNOWN""","""CPSF3L"""
4045,chr1,HAVANA,gene,1324756,1328897,.,+,.,ENSG00000224051,"""protein_coding""","""KNOWN""","""CPTP"""

In [40]:
def get_tss(gtf_df):
    tss = [] 
    for row in gtf_df.itertuples():
        
        if row[7] == '-':
            tss.append(row[5])
        else:
            tss.append(row[4])
    print(row)
    return tss

In [41]:
tss_genes = get_tss(use_genes)

Pandas(Index=2572696, _1='chrY', _2='HAVANA', _3='gene', _4=6910686, _5=7091683, _6='.', _7='+', _8='.', gene_id='ENSG00000092377', gene_type='"protein_coding"', gene_status='"KNOWN"', gene_name='"TBL1Y"')

In [42]:
orthologs.head()

,GeneType,hsa_gID,hsa_tID,hsa_pID,hsa_gName,hsa_tName,mmu_gID,mmu_tID,mmu_pID,mmu_gName,mmu_tName,HumanPercId,MousePercId
0,protein,ENSG00000136928,ENST00000259455,ENSP00000259455,GABBR2,GABBR2-001,ENSMUSG00000039809,ENSMUST00000107749,ENSMUSP00000103378,Gabbr2,Gabbr2-001,97.0,97.0
4,protein,ENSG00000224531,ENST00000416247,ENSP00000451866,SMIM13,C6orf228-002,ENSMUSG00000091264,ENSMUST00000165561,ENSMUSP00000130956,Smim13,BC024659-001,88.0,88.0
8,protein,ENSG00000161981,ENST00000383018,ENSP00000372482,SNRNP25,SNRNP25-201,ENSMUSG00000040767,ENSMUST00000039601,ENSMUSP00000046654,Snrnp25,Snrnp25-001,98.0,98.0
11,protein,ENSG00000125741,ENST00000323060,ENSP00000319817,OPA3,OPA3-202,ENSMUSG00000052214,ENSMUST00000063976,ENSMUSP00000069965,Opa3,Opa3-001,76.0,76.0
14,protein,ENSG00000015592,ENST00000350889,ENSP00000342538,STMN4,STMN4-001,ENSMUSG00000022044,ENSMUST00000074523,ENSMUSP00000074113,Stmn4,Stmn4-001,87.0,87.0

In [43]:
orthologs = orthologs.set_index("hsa_gID")

In [44]:
orthologs.head()

,GeneType,hsa_tID,hsa_pID,hsa_gName,hsa_tName,mmu_gID,mmu_tID,mmu_pID,mmu_gName,mmu_tName,HumanPercId,MousePercId
hsa_gID,,,,,,,,,,,,
ENSG00000136928,protein,ENST00000259455,ENSP00000259455,GABBR2,GABBR2-001,ENSMUSG00000039809,ENSMUST00000107749,ENSMUSP00000103378,Gabbr2,Gabbr2-001,97.0,97.0
ENSG00000224531,protein,ENST00000416247,ENSP00000451866,SMIM13,C6orf228-002,ENSMUSG00000091264,ENSMUST00000165561,ENSMUSP00000130956,Smim13,BC024659-001,88.0,88.0
ENSG00000161981,protein,ENST00000383018,ENSP00000372482,SNRNP25,SNRNP25-201,ENSMUSG00000040767,ENSMUST00000039601,ENSMUSP00000046654,Snrnp25,Snrnp25-001,98.0,98.0
ENSG00000125741,protein,ENST00000323060,ENSP00000319817,OPA3,OPA3-202,ENSMUSG00000052214,ENSMUST00000063976,ENSMUSP00000069965,Opa3,Opa3-001,76.0,76.0
ENSG00000015592,protein,ENST00000350889,ENSP00000342538,STMN4,STMN4-001,ENSMUSG00000022044,ENSMUST00000074523,ENSMUSP00000074113,Stmn4,Stmn4-001,87.0,87.0

In [46]:
use_gene_bed = pd.DataFrame(columns = ['chr', 'start_tss', 'end_tss', 'human_gid', 'mouse_gid'],
                        data=np.array([use_genes[0], np.array(tss_genes) -2000,
                              np.array(tss_genes)+2000, use_genes['gene_id'],
                              orthologs.loc[use_genes['gene_id'], "mmu_gID"]
                             ]).T)

In [48]:
use_gene_bed.head()

    chr start_tss  end_tss        human_gid           mouse_gid
0  chr1   1018123  1022123  ENSG00000188157  ENSMUSG00000041936
1  chr1   1271885  1275885  ENSG00000160087  ENSMUSG00000023286
2  chr1   1307609  1311609  ENSG00000131584  ENSMUSG00000029033
3  chr1   1322691  1326691  ENSG00000127054  ENSMUSG00000029034
4  chr1   1322756  1326756  ENSG00000224051  ENSMUSG00000029073

In [51]:
?pd.DataFrame.to_csv

Signature:
pd.DataFrame.to_csv(
    self,
    path_or_buf=None,
    sep=',',
    na_rep='',
    float_format=None,
    columns=None,
    header=True,
    index=True,
    index_label=None,
    mode='w',
    encoding=None,
    compression='infer',
    quoting=None,
    quotechar='"',
    line_terminator=None,
    chunksize=None,
    tupleize_cols=None,
    date_format=None,
    doublequote=True,
    escapechar=None,
    decimal='.',
)
Docstring:
Write object to a comma-separated values (csv) file.

.. versionchanged:: 0.24.0
    The order of arguments for Series was changed.

Parameters
----------
path_or_buf : str or file handle, default None
    File path or object, if None is provided the result is returned as
    a string.  If a file object is passed it should be opened with
    `newline=''`, disabling universal newlines.

    .. versionchanged:: 0.24.0

       Was previously named "path" for Series.

sep : str, default ','
    String of length 1. Field delimiter for the output file.
na_rep : str, default ''
    Missing data representation.
float_format : str, default None
    Format string for floating point numbers.
columns : sequence, optional
    Columns to write.
header : bool or list of str, default True
    Write out the column names. If a list of strings is given it is
    assumed to be aliases for the column names.

    .. versionchanged:: 0.24.0

       Previously defaulted to False for Series.

index : bool, default True
    Write row names (index).
index_label : str or sequence, or False, default None
    Column label for index column(s) if desired. If None is given, and
    `header` and `index` are True, then the index names are used. A
    sequence should be given if the object uses MultiIndex. If
    False do not print fields for index names. Use index_label=False
    for easier importing in R.
mode : str
    Python write mode, default 'w'.
encoding : str, optional
    A string representing the encoding to use in the output file,
    defaults to 'ascii' on Python 2 and 'utf-8' on Python 3.
compression : str, default 'infer'
    Compression mode among the following possible values: {'infer',
    'gzip', 'bz2', 'zip', 'xz', None}. If 'infer' and `path_or_buf`
    is path-like, then detect compression from the following
    extensions: '.gz', '.bz2', '.zip' or '.xz'. (otherwise no
    compression).

    .. versionchanged:: 0.24.0

       'infer' option added and set to default.

quoting : optional constant from csv module
    Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
    then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
    will treat them as non-numeric.
quotechar : str, default '\"'
    String of length 1. Character used to quote fields.
line_terminator : string, optional
    The newline character or character sequence to use in the output
    file. Defaults to `os.linesep`, which depends on the OS in which
    this method is called ('\n' for linux, '\r\n' for Windows, i.e.).

    .. versionchanged:: 0.24.0
chunksize : int or None
    Rows to write at a time.
tupleize_cols : bool, default False
    Write MultiIndex columns as a list of tuples (if True) or in
    the new, expanded format, where each MultiIndex column is a row
    in the CSV (if False).

    .. deprecated:: 0.21.0
       This argument will be removed and will always write each row
       of the multi-index as a separate row in the CSV file.
date_format : str, default None
    Format string for datetime objects.
doublequote : bool, default True
    Control quoting of `quotechar` inside a field.
escapechar : str, default None
    String of length 1. Character used to escape `sep` and `quotechar`
    when appropriate.
decimal : str, default '.'
    Character recognized as decimal separator. E.g. use ',' for
    European data.

Returns
-------
None or str
    If path_or_buf is None, returns the resulting csv format as a
    string. Otherwise returns None.

See Also
--------
read_csv : Load a CSV file into a DataFrame.
to_excel : Load an Excel file into a DataFrame.

Examples
--------
>>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
...                    'mask': ['red', 'purple'],
...                    'weapon': ['sai', 'bo staff']})
>>> df.to_csv(index=False)
'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'
File:      /cndd/earmand/conda_envs/multiplex/lib/python3.7/site-packages/pandas/core/generic.py
Type:      function

In [55]:
use_gene_bed.to_csv('use_gene_bed', sep='\t', header=False, index=False)

In [56]:
test = pd.read_csv('use_gene_bed', sep='\t', header=None)

In [57]:
test.head()

      0        1        2                3                   4
0  chr1  1018123  1022123  ENSG00000188157  ENSMUSG00000041936
1  chr1  1271885  1275885  ENSG00000160087  ENSMUSG00000023286
2  chr1  1307609  1311609  ENSG00000131584  ENSMUSG00000029033
3  chr1  1322691  1326691  ENSG00000127054  ENSMUSG00000029034
4  chr1  1322756  1326756  ENSG00000224051  ENSMUSG00000029073

In [ ]:
use_gene_bed['chr'] = use_genes[0]
use_gene_bed['start_tss'] = tss_genes - 2000
use_gene_bed['end_tss'] = tss_genes + 2000
use_gene_bed['human_gid'] = use_genes['gene_id']
use_gene_bed['mouse_gid'] = use_genes['mmu_gID']

In [ ]:
?str.strip

In [20]:
to_split = hg38[8]
splitted = [i.split(';') for i in to_split]

In [21]:
splitted[0]

['gene_id "ENSG00000223972.5"',
 ' gene_type "transcribed_unprocessed_pseudogene"',
 ' gene_status "KNOWN"',
 ' gene_name "DDX11L1"',
 ' level 2',
 ' havana_gene "OTTHUMG00000000961.2"',
 '']

In [25]:
gene_id = []
gene_type = []
gene_status = []
gene_name = []
gene_level = []
for strings in splitted:
    subsplit = [i.split(' ') for i in strings]
    gene_id.append(subsplit[0][1])
    gene_type.append(subsplit[1][2])
    gene_status.append(subsplit[2][2])
    gene_name.append(subsplit[3][2])
    gene_level.append(subsplit[4][2])

In [24]:
splitted_2[1]

NameError: name 'splitted_2' is not defined

In [26]:
hg38['gene_id'] = gene_id
hg38['gene_type'] = gene_type
hg38['gene_status'] = gene_status
hg38['gene_name'] = gene_name

In [27]:
hg38.head()

,0,1,2,3,4,5,6,7,8,gene_id,gene_type,gene_status,gene_name
0,chr1,HAVANA,gene,11869,14409,.,+,.,"gene_id ""ENSG00000223972.5""; gene_type ""transc...","""ENSG00000223972.5""","""transcribed_unprocessed_pseudogene""","""KNOWN""","""DDX11L1"""
12,chr1,HAVANA,gene,14404,29570,.,-,.,"gene_id ""ENSG00000227232.5""; gene_type ""unproc...","""ENSG00000227232.5""","""unprocessed_pseudogene""","""KNOWN""","""WASH7P"""
25,chr1,ENSEMBL,gene,17369,17436,.,-,.,"gene_id ""ENSG00000278267.1""; gene_type ""miRNA""...","""ENSG00000278267.1""","""miRNA""","""KNOWN""","""MIR6859-1"""
28,chr1,HAVANA,gene,29554,31109,.,+,.,"gene_id ""ENSG00000243485.4""; gene_type ""lincRN...","""ENSG00000243485.4""","""lincRNA""","""KNOWN""","""MIR1302-2"""
38,chr1,HAVANA,gene,34554,36081,.,-,.,"gene_id ""ENSG00000237613.2""; gene_type ""lincRN...","""ENSG00000237613.2""","""lincRNA""","""KNOWN""","""FAM138A"""

In [ ]:
splitted_2 = [i.split(' ') for i in ]

In [53]:
splitted_2 = []
for i in splitted:
    splitted_2.append([j.split(' ') for j in i])

In [55]:
splitted_2[0][0]

['gene_id', '"ENSG00000223972.5"']

In [30]:
f = open('/cndd2/Public_Datasets/references/hg19/transcriptome/gencode.v19.annotation.gtf', 'r')

In [31]:
check = f.readline()

In [32]:
check

'##description: evidence-based annotation of the human genome (GRCh37), version 19 (Ensembl 74)\n'

In [ ]:
hg19.head()