In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [45]:
evals = pd.read_csv('/cndd2/ethan/projects/enh_gene_linkage/intergenic_corr/data/evals_w_fdr_100kb_12k_genes.tsv', sep='\t')

In [46]:
evals.head()

,Unnamed: 0,gene,ens,in_gene,val,val2,val_clustershuffled,val2_clustershuffled,dist,pvalues,...,fdr<100kb shuffled (cluster label),pvalues2,fdr2<100kb,fdr2<200kb,fdr2<500kb,fdr2<100kb shuffled (cluster label),fdr_mcg,fdr_mcg_corr,fdr_atac,fdr_atac_corr
0,94,ENSMUSG00000000001,147662,False,-0.039720,0.044097,-0.265784,-0.136448,92177,0.424733,...,1.095838,0.450781,0.744850,0.797258,0.876520,1.032819,0.726151,0.662643,0.744850,0.721180
1,95,ENSMUSG00000000001,147663,False,0.024620,0.051756,-0.380239,-0.101215,91955,0.499490,...,0.922071,0.439489,0.738874,0.792315,0.873352,1.051270,0.770029,0.835107,0.738874,0.702838
2,96,ENSMUSG00000000001,147664,False,-0.022212,0.074516,-0.081081,-0.112376,84155,0.445065,...,1.037449,0.406090,0.720486,0.776735,0.862787,1.112977,0.738378,0.711723,0.720486,0.647348
3,97,ENSMUSG00000000001,147665,False,-0.147171,0.017398,0.194660,-0.279352,76112,0.306660,...,1.762511,0.490344,0.765055,0.813756,0.886827,0.979848,0.648328,0.367841,0.765055,0.780787
4,98,ENSMUSG00000000001,147666,False,0.122880,0.122005,0.050224,0.120910,63221,0.611919,...,0.806321,0.338683,0.679892,0.742359,0.840268,1.285390,0.829016,1.028145,0.679892,0.528936

In [47]:
enhs = pd.read_csv('enhancers_lifted.bed', sep='\t', header=None)

In [48]:
genes = pd.read_csv('tss_lifted.bed', sep='\t', header=None)

In [49]:
enhs.head()

      0         1         2   3
0  chr8  55592914  55593008   5
1  chr8  55587811  55587820   7
2  chr8  55528337  55528612  10
3  chr8  55482940  55483094  17
4  chr8  55473255  55473498  19

In [71]:
enhs.shape

(126134, 4)

In [50]:
genes.head()

      0         1         2                   3
0  chr8  55102323  55102324  ENSMUSG00000051951
1  chr4  83273518  83273519  ENSMUSG00000102851
2  chr8  55409874  55409875  ENSMUSG00000103377
3  chr8  55288183  55288184  ENSMUSG00000089699
4  chr8  55230212  55230213  ENSMUSG00000103201

In [72]:
genes.shape

(33814, 4)

In [51]:
enhs_over = enhs[3].values
genes_over = genes[3].values

In [52]:
evals_over = evals.loc[evals.ens.isin(enhs_over)]

In [53]:
evals.shape

(875777, 23)

In [54]:
evals_over.shape

(423786, 23)

In [55]:
evals_over['gene'].isin(genes_over).sum()

369250

In [56]:
evals_over = evals_over.loc[evals_over['gene'].isin(genes_over)]

In [57]:
evals_over.shape[0]/evals.shape[0]

0.4216255964703343

In [58]:
evals_over.gene.unique().shape

(10210,)

In [59]:
evals.gene.unique().shape

(12033,)

In [60]:
evals_over.gene.unique().shape[0]/evals.gene.unique().shape[0]

0.8484999584476024

In [61]:
evals.shape

(875777, 23)

In [62]:
evals

,Unnamed: 0,gene,ens,in_gene,val,val2,val_clustershuffled,val2_clustershuffled,dist,pvalues,...,fdr<100kb shuffled (cluster label),pvalues2,fdr2<100kb,fdr2<200kb,fdr2<500kb,fdr2<100kb shuffled (cluster label),fdr_mcg,fdr_mcg_corr,fdr_atac,fdr_atac_corr
0,94,ENSMUSG00000000001,147662,False,-0.039720,0.044097,-0.265784,-0.136448,92177,0.424733,...,1.095838,0.450781,0.744850,0.797258,0.876520,1.032819,0.726151,0.662643,0.744850,0.721180
1,95,ENSMUSG00000000001,147663,False,0.024620,0.051756,-0.380239,-0.101215,91955,0.499490,...,0.922071,0.439489,0.738874,0.792315,0.873352,1.051270,0.770029,0.835107,0.738874,0.702838
2,96,ENSMUSG00000000001,147664,False,-0.022212,0.074516,-0.081081,-0.112376,84155,0.445065,...,1.037449,0.406090,0.720486,0.776735,0.862787,1.112977,0.738378,0.711723,0.720486,0.647348
3,97,ENSMUSG00000000001,147665,False,-0.147171,0.017398,0.194660,-0.279352,76112,0.306660,...,1.762511,0.490344,0.765055,0.813756,0.886827,0.979848,0.648328,0.367841,0.765055,0.780787
4,98,ENSMUSG00000000001,147666,False,0.122880,0.122005,0.050224,0.120910,63221,0.611919,...,0.806321,0.338683,0.679892,0.742359,0.840268,1.285390,0.829016,1.028145,0.679892,0.528936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875772,1710095,ENSMUSG00000115850,78283,False,0.161615,0.026808,0.069264,-0.125506,469878,0.654901,...,0.791769,0.476363,0.757885,0.807961,0.883140,0.996857,0.974086,1.230264,0.967274,0.970322
875773,1710096,ENSMUSG00000115850,78287,False,-0.459897,0.395339,0.165773,0.428165,480739,0.068117,...,44.119962,0.068795,0.419103,0.508515,0.661389,7.291341,0.871471,0.019740,0.899924,0.123411
875774,1710097,ENSMUSG00000115850,78288,False,-0.551154,0.413065,0.153518,0.419630,481271,0.033363,...,221.371505,0.059522,0.401647,0.491075,0.647139,8.547065,0.843967,0.003787,0.896291,0.104850
875775,1710098,ENSMUSG00000115850,78289,False,0.308458,0.025495,-0.160302,-0.178685,484028,0.800713,...,0.826422,0.478306,0.758867,0.808766,0.883628,0.994399,0.987616,1.195048,0.967315,0.972762
875776,1710099,ENSMUSG00000115850,78290,False,-0.251122,0.006237,0.182843,-0.227705,484424,0.207834,...,3.631316,0.506940,0.773270,0.820363,0.891220,0.961649,0.921313,0.253709,0.969153,1.007801

# check corr pairs vs other

In [63]:
evals_over.head()

,Unnamed: 0,gene,ens,in_gene,val,val2,val_clustershuffled,val2_clustershuffled,dist,pvalues,...,fdr<100kb shuffled (cluster label),pvalues2,fdr2<100kb,fdr2<200kb,fdr2<500kb,fdr2<100kb shuffled (cluster label),fdr_mcg,fdr_mcg_corr,fdr_atac,fdr_atac_corr
2,96,ENSMUSG00000000001,147664,False,-0.022212,0.074516,-0.081081,-0.112376,84155,0.445065,...,1.037449,0.406090,0.720486,0.776735,0.862787,1.112977,0.738378,0.711723,0.720486,0.647348
3,97,ENSMUSG00000000001,147665,False,-0.147171,0.017398,0.194660,-0.279352,76112,0.306660,...,1.762511,0.490344,0.765055,0.813756,0.886827,0.979848,0.648328,0.367841,0.765055,0.780787
4,98,ENSMUSG00000000001,147666,False,0.122880,0.122005,0.050224,0.120910,63221,0.611919,...,0.806321,0.338683,0.679892,0.742359,0.840268,1.285390,0.829016,1.028145,0.679892,0.528936
8,102,ENSMUSG00000000001,147675,False,-0.122442,0.055477,0.222891,0.111281,29807,0.332837,...,1.545717,0.434006,0.735891,0.789836,0.871747,1.060819,0.666794,0.431380,0.735891,0.693699
10,104,ENSMUSG00000000001,147677,False,-0.105373,0.339315,0.052194,0.020243,74655,0.351167,...,1.424248,0.104630,0.474576,0.562167,0.706455,4.425997,0.678669,0.476509,0.474576,0.107220

In [64]:
evals_over.loc[evals_over.fdr_atac < .2].shape

(1941, 23)

In [65]:
evals_over.loc[evals_over.fdr_mcg < .2].shape

(4098, 23)

In [66]:
evals_over.loc[np.logical_or(evals_over.fdr_mcg < .2, evals_over.fdr_atac < .2)].shape

(5301, 23)

In [67]:
evals_over.loc[np.logical_and(evals_over.fdr_mcg < .2, evals_over.fdr_atac < .2)].shape

(738, 23)

In [68]:
print(evals_over.loc[evals_over.fdr_atac_corr < .005].shape, evals_over.loc[evals_over.fdr_mcg_corr < .005].shape, evals_over.loc[np.logical_or(evals_over.fdr_mcg_corr < .005, evals_over.fdr_atac_corr < .005)].shape, evals_over.loc[np.logical_and(evals_over.fdr_mcg_corr < .005, evals_over.fdr_atac_corr < .005)].shape)

(9097, 23) (29287, 23) (33704, 23) (4680, 23)

In [69]:
evals_double_linked = evals_over.loc[np.logical_and(evals_over.fdr_mcg < .2, evals_over.fdr_atac < .2)]

In [70]:
evals_double_linked.head()

,Unnamed: 0,gene,ens,in_gene,val,val2,val_clustershuffled,val2_clustershuffled,dist,pvalues,...,fdr<100kb shuffled (cluster label),pvalues2,fdr2<100kb,fdr2<200kb,fdr2<500kb,fdr2<100kb shuffled (cluster label),fdr_mcg,fdr_mcg_corr,fdr_atac,fdr_atac_corr
620,6429,ENSMUSG00000000440,191527,False,-0.861910,0.639786,0.120473,-0.116096,67867,0.000033,...,32.967677,0.003941,0.187465,0.257964,0.403091,354.183590,0.015918,0.0,0.187465,0.000482
694,7069,ENSMUSG00000000531,87149,False,-0.668454,0.756428,-0.078017,-0.102528,9298,0.008691,...,8691.230337,0.000279,0.091332,0.140863,0.253408,40.369575,0.190117,0.0,0.091332,0.001936
782,7523,ENSMUSG00000000552,87348,True,-0.667579,0.663202,0.157019,-0.114345,6233,0.008809,...,8808.615568,0.002619,0.168716,0.238106,0.378572,341.042132,0.191217,0.0,0.168716,0.000430
785,7526,ENSMUSG00000000552,87351,True,-0.767152,0.716599,0.064887,-0.071452,2705,0.001337,...,1337.153158,0.000818,0.119200,0.176061,0.299562,118.224763,0.091469,0.0,0.119200,0.000863
1133,10508,ENSMUSG00000000861,32322,True,-0.726228,0.709815,0.027027,0.063793,5650,0.003292,...,3291.559689,0.000971,0.124942,0.183023,0.309366,140.334569,0.132479,0.0,0.124942,0.000762

In [35]:
evals_double_linked.val2.rank()

620        74.0
694       612.5
782       218.5
785       483.0
1133      446.5
          ...
163558    139.0
164625    182.5
166124    495.0
166218    182.5
292589    719.0
Name: val2, Length: 738, dtype: float64

In [36]:
look_evals = evals_double_linked
look_evals['idx_new'] = np.arange(evals_double_linked.shape[0])

/cndd/earmand/conda_envs/multiplex/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [37]:
look_evals['idx_new']

620         0
694         1
782         2
785         3
1133        4
         ...
163558    733
164625    734
166124    735
166218    736
292589    737
Name: idx_new, Length: 738, dtype: int64

In [82]:
look_evals.loc[look_evals.in_gene == False].sort_values('val', ascending=True).head(20)

,Unnamed: 0,gene,ens,in_gene,val,val2,val_clustershuffled,val2_clustershuffled,dist,pvalues,...,pvalues2,fdr2<100kb,fdr2<200kb,fdr2<500kb,fdr2<100kb shuffled (cluster label),fdr_mcg,fdr_mcg_corr,fdr_atac,fdr_atac_corr,idx_new
126042,1290045,ENSMUSG00000049225,153383,False,-0.933034,0.681147,0.032498,-0.023307,51267,6.049995e-07,...,0.001843,0.153869,0.219528,0.354424,266.199958,0.012556,0.0,0.153869,0.000495,548
6631,65110,ENSMUSG00000005102,132088,False,-0.927344,0.671518,-0.352664,0.158114,34121,8.109517e-07,...,0.002234,0.162214,0.230207,0.368159,322.784991,0.009302,0.0,0.162214,0.000430,30
127057,1300619,ENSMUSG00000049907,173223,False,-0.919904,0.735420,-0.055258,-0.027902,5250,1.080274e-06,...,0.000514,0.108474,0.162519,0.281726,74.310241,0.006963,0.0,0.108474,0.001249,554
137290,1395159,ENSMUSG00000056708,12845,False,-0.910931,0.712222,0.181967,0.183062,48176,1.561897e-06,...,0.000917,0.123065,0.180760,0.306193,132.489154,0.005947,0.0,0.123065,0.000795,623
55589,568823,ENSMUSG00000027347,131992,False,-0.906335,0.705219,0.089397,-0.019805,43873,1.811416e-06,...,0.001090,0.129713,0.188917,0.317040,157.421081,0.005116,0.0,0.129713,0.000705,230
154719,1577526,ENSMUSG00000085516,32345,False,-0.901521,0.649415,0.132728,0.064887,54111,2.072817e-06,...,0.003340,0.178496,0.248656,0.391834,344.004429,0.004447,0.0,0.178496,0.000465,707
156066,1589227,ENSMUSG00000086612,32345,False,-0.900427,0.632126,0.079330,0.167086,3308,2.132226e-06,...,0.004489,0.195342,0.266804,0.413839,366.260280,0.004337,0.0,0.195342,0.000490,709
49494,504695,ENSMUSG00000026141,1600,False,-0.884889,0.705438,0.356166,0.092680,2567,7.684099e-06,...,0.001084,0.129473,0.188619,0.316662,156.568989,0.007757,0.0,0.129473,0.000707,188
51114,520858,ENSMUSG00000026458,11049,False,-0.882701,0.734107,-0.002079,0.046723,10154,8.753466e-06,...,0.000532,0.109213,0.163527,0.283015,76.861372,0.008176,0.0,0.109213,0.001216,194
134990,1373722,ENSMUSG00000055010,32331,False,-0.878543,0.628843,0.061823,0.065762,26178,1.115641e-05,...,0.004731,0.198502,0.270385,0.418165,371.319320,0.009057,0.0,0.198502,0.000493,607
38698,392599,ENSMUSG00000023927,100751,False,-0.877886,0.698873,0.154612,-0.071890,97970,1.176238e-05,...,0.001261,0.135999,0.196642,0.326771,182.131737,0.009313,0.0,0.135999,0.000639,137
60101,614379,ENSMUSG00000028266,151047,False,-0.876792,0.820768,0.115002,0.056790,18149,1.277234e-05,...,0.000029,0.058581,0.085705,0.171398,4.160261,0.009714,0.0,0.058581,0.012047,241
101003,1041433,ENSMUSG00000038418,108089,False,-0.875698,0.704563,0.119378,-0.004486,5700,1.378230e-05,...,0.001107,0.130423,0.189795,0.318156,159.977355,0.010084,0.0,0.130423,0.000697,429
98823,1019202,ENSMUSG00000037984,185928,False,-0.875479,0.811577,0.150892,0.039063,5153,1.398429e-05,...,0.000043,0.062317,0.093017,0.181203,6.176348,0.010155,0.0,0.062317,0.008632,410
103826,1070095,ENSMUSG00000039156,171584,False,-0.872634,0.870883,-0.051100,0.152205,55618,1.661018e-05,...,0.000002,0.016147,0.032843,0.080418,0.236209,0.010985,0.0,0.016147,0.058484,440
60099,614377,ENSMUSG00000028266,151045,False,-0.871321,0.730386,0.069045,0.083707,19643,1.782213e-05,...,0.000582,0.111109,0.166108,0.286296,84.089578,0.011320,0.0,0.111109,0.001130,239
50248,511553,ENSMUSG00000026259,7751,False,-0.863880,0.706532,0.009082,0.191815,30824,2.943877e-05,...,0.001054,0.128246,0.187098,0.314721,152.308531,0.014987,0.0,0.128246,0.000720,193
620,6429,ENSMUSG00000000440,191527,False,-0.861910,0.639786,0.120473,-0.116096,67867,3.296768e-05,...,0.003941,0.187465,0.257964,0.403091,354.183590,0.015918,0.0,0.187465,0.000482,0
15884,164109,ENSMUSG00000018648,38541,False,-0.857534,0.804355,0.051100,0.188533,73173,4.272394e-05,...,0.000056,0.066423,0.100721,0.192335,8.094142,0.018302,0.0,0.066423,0.007021,67
60100,614378,ENSMUSG00000028266,151046,False,-0.857315,0.742641,0.157019,0.090272,18639,4.335367e-05,...,0.000424,0.103715,0.156395,0.273594,61.206900,0.018453,0.0,0.103715,0.001450,240

In [144]:
look_evals.gene.unique()

array(['ENSMUSG00000000440', 'ENSMUSG00000000531', 'ENSMUSG00000001985',
       'ENSMUSG00000005089', 'ENSMUSG00000005102', 'ENSMUSG00000005580',
       'ENSMUSG00000006494', 'ENSMUSG00000009734', 'ENSMUSG00000014496',
       'ENSMUSG00000016637', 'ENSMUSG00000016933', 'ENSMUSG00000017493',
       'ENSMUSG00000018648', 'ENSMUSG00000019841', 'ENSMUSG00000019960',
       'ENSMUSG00000020042', 'ENSMUSG00000020064', 'ENSMUSG00000020173',
       'ENSMUSG00000020580', 'ENSMUSG00000020811', 'ENSMUSG00000020873',
       'ENSMUSG00000021203', 'ENSMUSG00000021215', 'ENSMUSG00000021224',
       'ENSMUSG00000021540', 'ENSMUSG00000021701', 'ENSMUSG00000021709',
       'ENSMUSG00000021743', 'ENSMUSG00000021974', 'ENSMUSG00000021994',
       'ENSMUSG00000022044', 'ENSMUSG00000022089', 'ENSMUSG00000022234',
       'ENSMUSG00000022237', 'ENSMUSG00000022342', 'ENSMUSG00000022602',
       'ENSMUSG00000023009', 'ENSMUSG00000023927', 'ENSMUSG00000024143',
       'ENSMUSG00000024617', 'ENSMUSG00000025478', 'ENSMUSG00000025795',
       'ENSMUSG00000026141', 'ENSMUSG00000026155', 'ENSMUSG00000026259',
       'ENSMUSG00000026458', 'ENSMUSG00000026587', 'ENSMUSG00000026833',
       'ENSMUSG00000026915', 'ENSMUSG00000027132', 'ENSMUSG00000027194',
       'ENSMUSG00000027273', 'ENSMUSG00000027297', 'ENSMUSG00000027298',
       'ENSMUSG00000027304', 'ENSMUSG00000027347', 'ENSMUSG00000027639',
       'ENSMUSG00000027649', 'ENSMUSG00000027655', 'ENSMUSG00000028266',
       'ENSMUSG00000029861', 'ENSMUSG00000029863', 'ENSMUSG00000030098',
       'ENSMUSG00000030310', 'ENSMUSG00000030613', 'ENSMUSG00000030846',
       'ENSMUSG00000030898', 'ENSMUSG00000031626', 'ENSMUSG00000031847',
       'ENSMUSG00000032827', 'ENSMUSG00000033278', 'ENSMUSG00000033590',
       'ENSMUSG00000033726', 'ENSMUSG00000033730', 'ENSMUSG00000033763',
       'ENSMUSG00000033953', 'ENSMUSG00000033955', 'ENSMUSG00000034101',
       'ENSMUSG00000034751', 'ENSMUSG00000035093', 'ENSMUSG00000036062',
       'ENSMUSG00000036304', 'ENSMUSG00000036478', 'ENSMUSG00000037032',
       'ENSMUSG00000037104', 'ENSMUSG00000037610', 'ENSMUSG00000037761',
       'ENSMUSG00000037833', 'ENSMUSG00000037843', 'ENSMUSG00000037855',
       'ENSMUSG00000037984', 'ENSMUSG00000038256', 'ENSMUSG00000038370',
       'ENSMUSG00000038388', 'ENSMUSG00000038418', 'ENSMUSG00000039156',
       'ENSMUSG00000039354', 'ENSMUSG00000039512', 'ENSMUSG00000039741',
       'ENSMUSG00000039852', 'ENSMUSG00000040943', 'ENSMUSG00000041544',
       'ENSMUSG00000041695', 'ENSMUSG00000041773', 'ENSMUSG00000041889',
       'ENSMUSG00000042105', 'ENSMUSG00000042429', 'ENSMUSG00000043067',
       'ENSMUSG00000044465', 'ENSMUSG00000044949', 'ENSMUSG00000045287',
       'ENSMUSG00000045515', 'ENSMUSG00000046546', 'ENSMUSG00000046572',
       'ENSMUSG00000047881', 'ENSMUSG00000048251', 'ENSMUSG00000048285',
       'ENSMUSG00000048458', 'ENSMUSG00000048482', 'ENSMUSG00000049225',
       'ENSMUSG00000049387', 'ENSMUSG00000049866', 'ENSMUSG00000049907',
       'ENSMUSG00000050271', 'ENSMUSG00000050891', 'ENSMUSG00000052584',
       'ENSMUSG00000052707', 'ENSMUSG00000053025', 'ENSMUSG00000053310',
       'ENSMUSG00000054364', 'ENSMUSG00000054863', 'ENSMUSG00000055010',
       'ENSMUSG00000055435', 'ENSMUSG00000056708', 'ENSMUSG00000057133',
       'ENSMUSG00000059713', 'ENSMUSG00000062373', 'ENSMUSG00000063659',
       'ENSMUSG00000064225', 'ENSMUSG00000067879', 'ENSMUSG00000069171',
       'ENSMUSG00000071341', 'ENSMUSG00000071359', 'ENSMUSG00000073394',
       'ENSMUSG00000073888', 'ENSMUSG00000073889', 'ENSMUSG00000074354',
       'ENSMUSG00000074622', 'ENSMUSG00000074637', 'ENSMUSG00000074754',
       'ENSMUSG00000075224', 'ENSMUSG00000075334', 'ENSMUSG00000075478',
       'ENSMUSG00000078695', 'ENSMUSG00000079434', 'ENSMUSG00000079546',
       'ENSMUSG00000084764', 'ENSMUSG00000084978', 'ENSMUSG00000085516',
       'ENSMUSG00000086612', 'ENSMUSG00000087006', 'ENSMUSG00000087143',
       'ENSMUSG00000087413', 'ENSMUSG00000090063', 'ENSMUSG00000095139',
       'ENSMUSG00000096948', 'ENSMUSG00000097840', 'ENSMUSG00000105797',
       'ENSMUSG00000043079'], dtype=object)

In [87]:
look_evals.loc[look_evals.in_gene == False].sort_values('dist', ascending=False).head(20)

,Unnamed: 0,gene,ens,in_gene,val,val2,val_clustershuffled,val2_clustershuffled,dist,pvalues,...,pvalues2,fdr2<100kb,fdr2<200kb,fdr2<500kb,fdr2<100kb shuffled (cluster label),fdr_mcg,fdr_mcg_corr,fdr_atac,fdr_atac_corr,idx_new
292589,1195876,ENSMUSG00000043079,111311,False,-0.817923,0.819674,-0.092023,-0.156363,164479,0.000273,...,0.000030,0.058496,0.085355,0.170719,4.323135,0.184492,0.0,0.148996,0.029486,737
10389,103234,ENSMUSG00000009734,55548,False,-0.699748,0.708502,-0.151111,0.023526,99654,0.005316,...,0.001001,0.125922,0.184203,0.311008,144.639706,0.157557,0.0,0.125922,0.000745,51
42825,435759,ENSMUSG00000024617,111315,False,-0.802167,0.631907,0.105154,-0.099464,99361,0.000480,...,0.004505,0.195559,0.267051,0.414139,366.609936,0.058717,0.0,0.195559,0.000490,161
153238,1564976,ENSMUSG00000079546,94698,False,-0.765182,0.635846,0.030091,-0.392713,98984,0.001408,...,0.004215,0.191465,0.262384,0.408465,360.021549,0.093474,0.0,0.191465,0.000486,699
135564,1378740,ENSMUSG00000055435,214799,False,-0.740891,0.669767,0.256155,-0.121129,98927,0.002476,...,0.002309,0.163569,0.231905,0.370364,333.524431,0.118253,0.0,0.163569,0.000420,614
31432,323078,ENSMUSG00000022089,72102,False,-0.701937,0.764307,-0.145202,-0.060948,98607,0.005128,...,0.000221,0.085264,0.133128,0.245178,31.894502,0.155700,0.0,0.085264,0.002287,113
140399,1428098,ENSMUSG00000059713,164523,False,-0.756647,0.737827,-0.040814,0.044534,98292,0.001733,...,0.000482,0.107008,0.160516,0.279153,69.633167,0.101769,0.0,0.107008,0.001315,648
83867,869901,ENSMUSG00000033278,102170,False,-0.683992,0.675019,0.104278,0.081738,98227,0.006896,...,0.002086,0.159294,0.226534,0.363372,301.306110,0.173832,0.0,0.159294,0.000452,321
153239,1564977,ENSMUSG00000079546,94699,False,-0.703687,0.658387,0.115877,-0.302112,98014,0.004977,...,0.002853,0.172043,0.242045,0.383787,340.095327,0.154148,0.0,0.172043,0.000446,700
38698,392599,ENSMUSG00000023927,100751,False,-0.877886,0.698873,0.154612,-0.071890,97970,0.000012,...,0.001261,0.135999,0.196642,0.326771,182.131737,0.009313,0.0,0.135999,0.000639,137
140397,1428096,ENSMUSG00000059713,164521,False,-0.717256,0.729730,-0.073422,0.016741,97226,0.003890,...,0.000591,0.111417,0.166526,0.286824,85.365144,0.141338,0.0,0.111417,0.001117,647
31434,323080,ENSMUSG00000022089,72104,False,-0.712441,0.677645,0.016304,-0.076704,96987,0.004260,...,0.001974,0.156897,0.223507,0.359405,285.196949,0.146053,0.0,0.156897,0.000471,114
54412,556259,ENSMUSG00000027132,131440,False,-0.720320,0.706095,0.025714,0.259875,96257,0.003675,...,0.001066,0.128742,0.187714,0.315508,154.012714,0.138351,0.0,0.128742,0.000715,209
39967,406321,ENSMUSG00000024143,104505,False,-0.738046,0.644819,0.136448,0.033155,95487,0.002621,...,0.003622,0.182769,0.253103,0.397232,348.668282,0.120999,0.0,0.182769,0.000474,154
152577,1556926,ENSMUSG00000078695,39996,False,-0.669110,0.632345,0.140825,-0.017179,95415,0.008613,...,0.004473,0.195123,0.266555,0.413538,365.908780,0.189480,0.0,0.195123,0.000490,695
153124,1563551,ENSMUSG00000079434,7751,False,-0.822300,0.769559,0.100777,0.160521,94805,0.000232,...,0.000187,0.081639,0.128460,0.240824,27.031334,0.041971,0.0,0.081639,0.002584,698
153123,1563550,ENSMUSG00000079434,7750,False,-0.759273,0.785972,0.282854,0.218514,94176,0.001620,...,0.000109,0.075470,0.118358,0.224648,15.720605,0.098835,0.0,0.075470,0.004107,697
153862,1570374,ENSMUSG00000084978,41220,False,-0.711347,0.629062,0.028997,-0.078893,94147,0.004344,...,0.004715,0.198298,0.270154,0.417888,370.994029,0.147052,0.0,0.198298,0.000492,704
74283,768044,ENSMUSG00000030898,200745,False,-0.684648,0.715286,-0.230550,-0.013240,93842,0.006823,...,0.000848,0.120427,0.177558,0.301682,122.504080,0.173109,0.0,0.120427,0.000841,292
97148,1005978,ENSMUSG00000037610,140871,False,-0.692745,0.670642,-0.183499,-0.039282,93636,0.005985,...,0.002271,0.162900,0.231067,0.369276,328.154711,0.164650,0.0,0.162900,0.000425,388

In [91]:
look_evals= look_evals.loc[look_evals.in_gene==False]

In [95]:
stim_2_enhs = look_evals.loc[look_evals.gene == 'ENSMUSG00000039156'].ens.values

# possible_examples
- BCL9/ENSMUSG00000038256 146496
- RASL11b 
- SYNPO/ENSMUSG00000043079 111311
- LMO4/ENSMUSG00000028266 151047

# get human coordinates

In [39]:
genes.head()

      0         1         2                   3
0  chr8  55102323  55102324  ENSMUSG00000051951
1  chr4  83273518  83273519  ENSMUSG00000102851
2  chr8  55409874  55409875  ENSMUSG00000103377
3  chr8  55288183  55288184  ENSMUSG00000089699
4  chr8  55230212  55230213  ENSMUSG00000103201

In [40]:
enhs.head()

      0         1         2   3
0  chr8  55592914  55593008   5
1  chr8  55587811  55587820   7
2  chr8  55528337  55528612  10
3  chr8  55482940  55483094  17
4  chr8  55473255  55473498  19

In [104]:
enhs.set_index(3).loc[[146496, 111311, 151047, 171584, 171583, 171582, 97738, 153383, 111311]].reset_index()

        3     0          1          2
0  146496  chr1  147543826  147544305
1  111311  chr5  150385845  150386911
2  151047  chr1   87346989   87347476
3  171584  chr4   26804388   26805669
4  171583  chr4   26803628   26804306
5  171582  chr4   26803078   26803600
6   97738  chr6  163419865  163421088
7  153383  chr8   93844483   93845662
8  111311  chr5  150385845  150386911

In [89]:
genes.set_index(3).loc[["ENSMUSG00000028266", "ENSMUSG00000038256", "ENSMUSG00000043079", "ENSMUSG00000039156", "ENSMUSG00000039156", "ENSMUSG00000039156", "ENSMUSG00000062078", "ENSMUSG00000049225", "ENSMUSG00000043079"]]

                       0          1          2
3
ENSMUSG00000028266  chr1   87328847   87328848
ENSMUSG00000038256  chr1  147541511  147541512
ENSMUSG00000043079  chr5  150586082  150586083
ENSMUSG00000039156  chr4   26860771   26860772
ENSMUSG00000039156  chr4   26860771   26860772
ENSMUSG00000039156  chr4   26860771   26860772
ENSMUSG00000062078  chr6  163414653  163414654
ENSMUSG00000049225  chr8   93916924   93916925
ENSMUSG00000043079  chr5  150586082  150586083

In [81]:
87328848 - 87346989

-18141

In [86]:
93845662 -93916924

-71262

In [90]:
150586082 - 150385845

200237

In [115]:
genes

          0         1         2                   3
0      chr8  55102323  55102324  ENSMUSG00000051951
1      chr4  83273518  83273519  ENSMUSG00000102851
2      chr8  55409874  55409875  ENSMUSG00000103377
3      chr8  55288183  55288184  ENSMUSG00000089699
4      chr8  55230212  55230213  ENSMUSG00000103201
...     ...       ...       ...                 ...
33809  chrM     14672     14673  ENSMUSG00000064368
33810  chrM     14741     14742  ENSMUSG00000064369
33811  chrM     14747     14748  ENSMUSG00000064370
33812  chrM     15888     15889  ENSMUSG00000064371
33813  chrM     16032     16033  ENSMUSG00000064372

[33814 rows x 4 columns]

In [128]:
type(enh_df)

pandas.core.frame.DataFrame

In [129]:
type(gene_df)

pandas.core.frame.DataFrame

In [130]:
enh_df

        3     0         1         2
0  191527  chr3  12199199  12200057

In [132]:
gene_df

   index ENSMUSG00000000440
0      0               chr3
1      1           12287798
2      2           12287799

In [124]:
type(genes.set_index(3).loc[i])

pandas.core.series.Series

In [122]:
genes.set_index(3)

                       0         1         2
3
ENSMUSG00000051951  chr8  55102323  55102324
ENSMUSG00000102851  chr4  83273518  83273519
ENSMUSG00000103377  chr8  55409874  55409875
ENSMUSG00000089699  chr8  55288183  55288184
ENSMUSG00000103201  chr8  55230212  55230213

In [101]:
stim_2_plot =enhs.set_index(3).loc[stim_2_enhs].reset_index()

In [96]:
# plot enhs

In [103]:
look_evals.head()

,Unnamed: 0,gene,ens,in_gene,val,val2,val_clustershuffled,val2_clustershuffled,dist,pvalues,...,pvalues2,fdr2<100kb,fdr2<200kb,fdr2<500kb,fdr2<100kb shuffled (cluster label),fdr_mcg,fdr_mcg_corr,fdr_atac,fdr_atac_corr,idx_new
620,6429,ENSMUSG00000000440,191527,False,-0.861910,0.639786,0.120473,-0.116096,67867,0.000033,...,0.003941,0.187465,0.257964,0.403091,354.183590,0.015918,0.0,0.187465,0.000482,0
694,7069,ENSMUSG00000000531,87149,False,-0.668454,0.756428,-0.078017,-0.102528,9298,0.008691,...,0.000279,0.091332,0.140863,0.253408,40.369575,0.190117,0.0,0.091332,0.001936,1
2676,25396,ENSMUSG00000001985,163089,False,-0.709159,0.665828,-0.042784,-0.236021,69550,0.004512,...,0.002491,0.166703,0.235710,0.375387,341.636196,0.148975,0.0,0.166703,0.000421,11
2679,25399,ENSMUSG00000001985,163092,False,-0.776124,0.692745,-0.259000,-0.137105,59539,0.001063,...,0.001447,0.142677,0.204986,0.336688,209.006926,0.083769,0.0,0.142677,0.000584,12
6579,64943,ENSMUSG00000005089,130580,False,-0.758836,0.744173,0.146296,0.152205,58770,0.001636,...,0.000406,0.102533,0.154935,0.271591,58.590618,0.099198,0.0,0.102533,0.001497,24

# get examples for all possible genes

In [135]:
example_genes = look_evals.gene.unique()
coord_by_gene = {}
for i in example_genes:
    use_enhs = look_evals.loc[look_evals.gene == i].ens.values
    enh_df = enhs.loc[enhs[3].isin(use_enhs)]
    gene_df = genes.loc[genes[3]==i]

    use_df = pd.concat([enh_df, gene_df])
    
    use_df.columns = [ 'chrom', 'start', 'end', 'annot']
    
    coord_by_gene[i] = use_df

In [138]:
len(coord_by_gene)

169

In [140]:
import pickle

In [142]:
pickle.dump(coord_by_gene, open('data/plot_examples.pkl', 'wb'), protocol=pickle.HIGHEST_PROTOCOL)

In [113]:
gene_df

   index ENSMUSG00000000440
0      0               chr3
1      1           12287798
2      2           12287799

In [143]:
coord_by_gene[i]

      chrom      start        end               annot
60261  chr5  150385845  150386911              111311
30503  chr5  150586082  150586083  ENSMUSG00000043079