In [1]:
import sys
import importlib
sys.path.insert(0, '/cndd/fangming/CEMBA/snmcseq_dev')
sys.path.insert(0, '/cndd2/fangming/projects/scf_enhancers/scripts/scf_enhancer_paper')
from __init__ import *
import __init__jupyterlab
importlib.reload(__init__jupyterlab)
from __init__jupyterlab import *

import re 
import tqdm
import pickle
import collections
import itertools
import tables

from scipy import sparse
from scipy import stats
from scipy import optimize 
import scipy.cluster.hierarchy as sch
from statsmodels.stats.multitest import multipletests

import snmcseq_utils
importlib.reload(snmcseq_utils)

In [2]:
dirc = '/cndd2/Public_Datasets/Cusanovich_Trapnell_Shendure_Nature_2018'

# Cell type data 

Learned:
- neuorns are from cluster 5,15,29

In [3]:
with snmcseq_utils.cd(dirc):
    cellmeta = pd.read_csv('cell_metadata.txt', sep='\t')
    
print(cellmeta.shape)
print(cellmeta['id'].unique().shape)
print(cellmeta['cluster'].unique().shape)
cellmeta.head()

(81173, 11)
(85,)
(30,)

,cell,tissue,tissue.replicate,cluster,subset_cluster,tsne_1,tsne_2,subset_tsne1,subset_tsne2,id,cell_label
0,AGCGATAGAACGAATTCGCCTCCGACGGCAGGACGT,Lung,Lung2_62216,10,1,16.258044,17.056744,-14.448729,-3.100071,clusters_10.cluster_1,Hematopoietic progenitors
1,AGCGATAGAACGAATTCGTTGGTAGTCGATAGAGGC,Spleen,Spleen_62016,10,1,15.281495,16.108586,-15.238080,1.123518,clusters_10.cluster_1,Hematopoietic progenitors
2,AGCGATAGAACGCGCAGAAAGCTAGGTTAGGCGAAG,BoneMarrow,BoneMarrow_62016,10,1,17.039141,14.697498,-16.881654,5.244815,clusters_10.cluster_1,Hematopoietic progenitors
3,AGCGATAGAACGCGCAGAAAGCTAGGTTGTACTGAC,BoneMarrow,BoneMarrow_62016,10,1,10.646176,16.881202,4.437470,14.324422,clusters_10.cluster_1,Hematopoietic progenitors
4,AGCGATAGAACGCGCAGAAGCTTATAGGATAGAGGC,BoneMarrow,BoneMarrow_62216,10,1,10.975240,12.110841,9.064330,-11.660620,clusters_10.cluster_1,Hematopoietic progenitors

In [4]:
uniq_cellclusters = cellmeta.groupby(['tissue', 'cluster', 'subset_cluster', 'id', 'cell_label']).size().reset_index()#[['tissue', 'cluster', 'subset_cluster', 'id', 'cell_label']]
uniq_cellclusters = uniq_cellclusters.rename(columns={0: 'count'})
uniq_cellclusters

,tissue,cluster,subset_cluster,id,cell_label,count
0,BoneMarrow,1,1,clusters_1.cluster_1,Unknown,121
1,BoneMarrow,1,2,clusters_1.cluster_2,Unknown,105
2,BoneMarrow,1,3,clusters_1.cluster_3,Unknown,9
3,BoneMarrow,4,1,clusters_4.cluster_1,B cells,184
4,BoneMarrow,4,2,clusters_4.cluster_2,B cells,56
...,...,...,...,...,...,...
457,WholeBrain,27,2,clusters_27.cluster_2,Collisions,158
458,WholeBrain,27,3,clusters_27.cluster_3,Collisions,98
459,WholeBrain,28,2,clusters_28.cluster_2,Immature B cells,1
460,WholeBrain,29,1,clusters_29.cluster_1,Ex. neurons SCPN,64
461,WholeBrain,30,3,clusters_30.cluster_3,Collisions,21

In [5]:
# save to disk
uniq_cellclusters.to_csv(os.path.join(dirc, 'uniq_cellclusters.txt'), sep='\t', index=False)

In [6]:
relevant_types = uniq_cellclusters[uniq_cellclusters['cell_label'].str.contains('neuron')].sort_values('count', ascending=False)
relevant_types

,tissue,cluster,subset_cluster,id,cell_label,count
285,PreFrontalCortex,5,1,clusters_5.cluster_1,Ex. neurons CPN,1391
286,PreFrontalCortex,5,2,clusters_5.cluster_2,Ex. neurons SCPN,710
436,WholeBrain,15,1,clusters_15.cluster_1,Inhibitory neurons,611
287,PreFrontalCortex,5,3,clusters_5.cluster_3,Ex. neurons CThPN,609
316,PreFrontalCortex,29,1,clusters_29.cluster_1,Ex. neurons SCPN,450
422,WholeBrain,5,1,clusters_5.cluster_1,Ex. neurons CPN,439
437,WholeBrain,15,2,clusters_15.cluster_2,Inhibitory neurons,390
288,PreFrontalCortex,5,4,clusters_5.cluster_4,Ex. neurons CThPN,386
297,PreFrontalCortex,15,3,clusters_15.cluster_3,SOM+ Interneurons,386
424,WholeBrain,5,3,clusters_5.cluster_3,Ex. neurons CThPN,282
425,WholeBrain,5,4,clusters_5.cluster_4,Ex. neurons CThPN,261
423,WholeBrain,5,2,clusters_5.cluster_2,Ex. neurons SCPN,239
426,WholeBrain,5,5,clusters_5.cluster_5,Inhibitory neurons,204
49,Cerebellum,15,2,clusters_15.cluster_2,Inhibitory neurons,157
438,WholeBrain,15,3,clusters_15.cluster_3,SOM+ Interneurons,148
295,PreFrontalCortex,15,1,clusters_15.cluster_1,Inhibitory neurons,130
48,Cerebellum,15,1,clusters_15.cluster_1,Inhibitory neurons,108
296,PreFrontalCortex,15,2,clusters_15.cluster_2,Inhibitory neurons,100
289,PreFrontalCortex,5,5,clusters_5.cluster_5,Inhibitory neurons,90
460,WholeBrain,29,1,clusters_29.cluster_1,Ex. neurons SCPN,64
50,Cerebellum,15,3,clusters_15.cluster_3,SOM+ Interneurons,18
40,Cerebellum,5,5,clusters_5.cluster_5,Inhibitory neurons,16
179,LargeIntestine,15,1,clusters_15.cluster_1,Inhibitory neurons,14
251,Lung,15,1,clusters_15.cluster_1,Inhibitory neurons,4
335,SmallIntestine,15,1,clusters_15.cluster_1,Inhibitory neurons,2
39,Cerebellum,5,3,clusters_5.cluster_3,Ex. neurons CThPN,2
37,Cerebellum,5,1,clusters_5.cluster_1,Ex. neurons CPN,2
38,Cerebellum,5,2,clusters_5.cluster_2,Ex. neurons SCPN,1
252,Lung,15,2,clusters_15.cluster_2,Inhibitory neurons,1
336,SmallIntestine,15,3,clusters_15.cluster_3,SOM+ Interneurons,1
237,Lung,5,2,clusters_5.cluster_2,Ex. neurons SCPN,1
180,LargeIntestine,15,2,clusters_15.cluster_2,Inhibitory neurons,1
70,Cerebellum,29,1,clusters_29.cluster_1,Ex. neurons SCPN,1

In [7]:
relevant_types.groupby(['id', 'cell_label']).sum().drop(['cluster', 'subset_cluster'], axis=1)

                                          count
id                    cell_label
clusters_15.cluster_1 Inhibitory neurons    869
clusters_15.cluster_2 Inhibitory neurons    649
clusters_15.cluster_3 SOM+ Interneurons     553
clusters_29.cluster_1 Ex. neurons SCPN      515
clusters_5.cluster_1  Ex. neurons CPN      1832
clusters_5.cluster_2  Ex. neurons SCPN      951
clusters_5.cluster_3  Ex. neurons CThPN     893
clusters_5.cluster_4  Ex. neurons CThPN     647
clusters_5.cluster_5  Inhibitory neurons    310

# Filter master connnections
- by cluster 5,15,29
- by time

In [8]:
with snmcseq_utils.cd(dirc):
    masterconn = pd.read_csv('master_cicero_conns.txt', sep='\t')
    
masterconn.head()

,connection,Peak1,Peak2,coaccess,peak1.isproximal,peak1.tss.gene_name,peak1.tss.gene_id,peak2.isproximal,peak2.tss.gene_name,peak2.tss.gene_id,conn_type,cluster,subset_cluster,subcluster
0,chr10_100050458_100050896;chr10_100050979_1000...,chr10_100050458_100050896,chr10_100050979_100052296,0.295549,Yes,1700017N19Rik,ENSMUSG00000056912,Yes,1700017N19Rik,ENSMUSG00000056912,proximal_proximal,1,2,1_2
1,chr10_100050458_100050896;chr10_100050979_1000...,chr10_100050458_100050896,chr10_100050979_100052296,0.295549,Yes,1700017N19Rik,ENSMUSG00000056912,Yes,4930430F08Rik,ENSMUSG00000046567,proximal_proximal,1,2,1_2
2,chr10_100050458_100050896;chr10_100050979_1000...,chr10_100050458_100050896,chr10_100050979_100052296,0.295549,Yes,4930430F08Rik,ENSMUSG00000046567,Yes,1700017N19Rik,ENSMUSG00000056912,proximal_proximal,1,2,1_2
3,chr10_100050458_100050896;chr10_100050979_1000...,chr10_100050458_100050896,chr10_100050979_100052296,0.295549,Yes,4930430F08Rik,ENSMUSG00000046567,Yes,4930430F08Rik,ENSMUSG00000046567,proximal_proximal,1,2,1_2
4,chr10_100050979_100052296;chr10_100050458_1000...,chr10_100050979_100052296,chr10_100050458_100050896,0.295549,Yes,1700017N19Rik,ENSMUSG00000056912,Yes,1700017N19Rik,ENSMUSG00000056912,proximal_proximal,1,2,1_2

In [9]:
masterconn.shape

(17357676, 14)

In [10]:
masterconn['conn_type'].unique() #.isin([5, 15, 29])

array(['proximal_proximal', 'distal_distal', 'distal_proximal'],
      dtype=object)

In [11]:
filters = (
    (masterconn['cluster'].isin([5, 15, 29]))
    & (masterconn['conn_type']=='distal_proximal')
)
filtered_conn = masterconn[filters]
filtered_conn.shape

(828164, 14)

In [12]:
filtered_conn['idx'] = np.arange(len(filtered_conn)) 
filtered_conn

<ipython-input-12-0f9646abd971>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_conn['idx'] = np.arange(len(filtered_conn))

,connection,Peak1,Peak2,coaccess,peak1.isproximal,peak1.tss.gene_name,peak1.tss.gene_id,peak2.isproximal,peak2.tss.gene_name,peak2.tss.gene_id,conn_type,cluster,subset_cluster,subcluster,idx
259442,chr10_100162958_100163698;chr10_99949234_99950834,chr10_100162958_100163698,chr10_99949234_99950834,0.211937,NaN,NaN,NaN,Yes,Cep290,ENSMUSG00000019971,distal_proximal,5,3,5_3,0
259443,chr10_100162958_100163698;chr10_99949234_99950834,chr10_100162958_100163698,chr10_99949234_99950834,0.211937,NaN,NaN,NaN,Yes,Tmtc3,ENSMUSG00000036676,distal_proximal,5,3,5_3,1
259452,chr10_10039776_10041748;chr10_10407868_10409865,chr10_10039776_10041748,chr10_10407868_10409865,0.360986,NaN,NaN,NaN,Yes,Gm10828,ENSMUSG00000075319,distal_proximal,5,3,5_3,2
259454,chr10_10039776_10041748;chr10_9818319_9818723,chr10_10039776_10041748,chr10_9818319_9818723,0.256415,NaN,NaN,NaN,Yes,U1,ENSMUSG00000065876,distal_proximal,5,3,5_3,3
259457,chr10_10042771_10043156;chr10_10407868_10409865,chr10_10042771_10043156,chr10_10407868_10409865,0.218072,NaN,NaN,NaN,Yes,Gm10828,ENSMUSG00000075319,distal_proximal,5,3,5_3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15598389,chrX_98834652_98836840;chrX_98541652_98542457,chrX_98834652_98836840,chrX_98541652_98542457,0.227231,Yes,Ogt,ENSMUSG00000034160,NaN,NaN,NaN,distal_proximal,29,1,29_1,828159
15598395,chrX_99213985_99215526;chrX_99313957_99315201,chrX_99213985_99215526,chrX_99313957_99315201,0.389015,NaN,NaN,NaN,Yes,Pin4,ENSMUSG00000079480,distal_proximal,29,1,29_1,828160
15598396,chrX_99229950_99230313;chrX_99383845_99385084,chrX_99229950_99230313,chrX_99383845_99385084,0.284536,NaN,NaN,NaN,Yes,Rps4x,ENSMUSG00000031320,distal_proximal,29,1,29_1,828161
15598398,chrX_99313957_99315201;chrX_99213985_99215526,chrX_99313957_99315201,chrX_99213985_99215526,0.389015,Yes,Pin4,ENSMUSG00000079480,NaN,NaN,NaN,distal_proximal,29,1,29_1,828162
15598401,chrX_99383845_99385084;chrX_99229950_99230313,chrX_99383845_99385084,chrX_99229950_99230313,0.284536,Yes,Rps4x,ENSMUSG00000031320,NaN,NaN,NaN,distal_proximal,29,1,29_1,828163

In [13]:
filtered_conn.to_csv(os.path.join(dirc, 'master_cicero_conns_allneurons_distalToProximal.txt'), 
                     sep='\t',
                     na_rep='NA',
                    )

# Clean up filtered connections
- check and understand
    - some duplicated connections - same connections annotated with different genes
    - no reciprocal duplicates 
- NOT remove duplicates; keep connections only
- liftOver connections to mm10
- conform to the existing format

In [14]:
filtered_conn['conn_type'].unique()
filtered_conn['peak1.isproximal'].unique()

array([nan, 'Yes'], dtype=object)

In [15]:
filtered_conn.shape

(828164, 15)

In [16]:
# dedupf_conn = filtered_conn.drop_duplicates(subset=['connection'])
# dedupf_conn.shape

In [17]:
# # agree 
# (~(dedupf_conn['connection'] == dedupf_conn['Peak1']+';'+dedupf_conn['Peak2'])).sum()

In [18]:
# # test if there are reciprocal duplicates?
# test_conns = np.hstack([
#     dedupf_conn['connection'].values, 
#     (dedupf_conn['Peak2']+';'+dedupf_conn['Peak1']).values,
#     ])
# np.unique(test_conns).shape
# # no

In [19]:
# dedupf_conn.to_csv(os.path.join(dirc, 'master_cicero_conns_allneurons_distalToProximal_dedup.txt'), 
#                      sep='\t',
#                      na_rep='NA',
#                     )

### Prep bed to liftOver

In [20]:
def get_region(region):
    chrom, start, end = region.split('_')
    return chrom, start, end

In [21]:
peak1_bed = pd.DataFrame()
peak1_bed['chrom'] = filtered_conn['Peak1'].apply(lambda x: get_region(x)[0])
peak1_bed['start'] = filtered_conn['Peak1'].apply(lambda x: get_region(x)[1])
peak1_bed['end'] = filtered_conn['Peak1'].apply(lambda x: get_region(x)[2])
peak1_bed['idx'] = filtered_conn['idx']

print(peak1_bed.shape)
peak1_bed.to_csv(os.path.join(dirc, 'liftover_allneurons_distaltoproximal', 'peak1.bed'),
                 sep='\t', header=False, index=False,
                )

peak2_bed = pd.DataFrame()
peak2_bed['chrom'] = filtered_conn['Peak2'].apply(lambda x: get_region(x)[0])
peak2_bed['start'] = filtered_conn['Peak2'].apply(lambda x: get_region(x)[1])
peak2_bed['end'] = filtered_conn['Peak2'].apply(lambda x: get_region(x)[2])
peak2_bed['idx'] = filtered_conn['idx']

print(peak2_bed.shape)
peak2_bed.to_csv(os.path.join(dirc, 'liftover_allneurons_distaltoproximal', 'peak2.bed'),
                 sep='\t', header=False, index=False,
                )

(828164, 4)
(828164, 4)

### liftOver

In [22]:
res1 = pd.read_csv(os.path.join(dirc, 'liftover_allneurons_distaltoproximal', 'peak1_mm10.bed'), 
                   sep='\t', header=None)
res2 = pd.read_csv(os.path.join(dirc, 'liftover_allneurons_distaltoproximal', 'peak2_mm10.bed'), 
                   sep='\t', header=None)
    
conn_mm10 = pd.merge(res1, res2, on=3).rename(columns={
    3: 'idx', 
    
    '0_x': 'peak1_chr_mm10',
    '1_x': 'peak1_start_mm10',
    '2_x': 'peak1_end_mm10',
    
    '0_y': 'peak2_chr_mm10',
    '1_y': 'peak2_start_mm10',
    '2_y': 'peak2_end_mm10',
})

print(res1.shape, res2.shape, conn_mm10.shape)
conn_mm10.head()

(828146, 4) (828146, 4) (828128, 7)

,peak1_chr_mm10,peak1_start_mm10,peak1_end_mm10,idx,peak2_chr_mm10,peak2_start_mm10,peak2_end_mm10
0,chr10,100700324,100701064,0,chr10,100486600,100488200
1,chr10,100700324,100701064,1,chr10,100486600,100488200
2,chr10,10319978,10321950,2,chr10,10688070,10690067
3,chr10,10319978,10321950,3,chr10,10098521,10098925
4,chr10,10322973,10323358,4,chr10,10688070,10690067

In [23]:
conn_mm10 = pd.merge(conn_mm10, filtered_conn, on='idx')
print(conn_mm10.shape)
conn_mm10.head()

(828128, 21)

,peak1_chr_mm10,peak1_start_mm10,peak1_end_mm10,idx,peak2_chr_mm10,peak2_start_mm10,peak2_end_mm10,connection,Peak1,Peak2,...,peak1.isproximal,peak1.tss.gene_name,peak1.tss.gene_id,peak2.isproximal,peak2.tss.gene_name,peak2.tss.gene_id,conn_type,cluster,subset_cluster,subcluster
0,chr10,100700324,100701064,0,chr10,100486600,100488200,chr10_100162958_100163698;chr10_99949234_99950834,chr10_100162958_100163698,chr10_99949234_99950834,...,NaN,NaN,NaN,Yes,Cep290,ENSMUSG00000019971,distal_proximal,5,3,5_3
1,chr10,100700324,100701064,1,chr10,100486600,100488200,chr10_100162958_100163698;chr10_99949234_99950834,chr10_100162958_100163698,chr10_99949234_99950834,...,NaN,NaN,NaN,Yes,Tmtc3,ENSMUSG00000036676,distal_proximal,5,3,5_3
2,chr10,10319978,10321950,2,chr10,10688070,10690067,chr10_10039776_10041748;chr10_10407868_10409865,chr10_10039776_10041748,chr10_10407868_10409865,...,NaN,NaN,NaN,Yes,Gm10828,ENSMUSG00000075319,distal_proximal,5,3,5_3
3,chr10,10319978,10321950,3,chr10,10098521,10098925,chr10_10039776_10041748;chr10_9818319_9818723,chr10_10039776_10041748,chr10_9818319_9818723,...,NaN,NaN,NaN,Yes,U1,ENSMUSG00000065876,distal_proximal,5,3,5_3
4,chr10,10322973,10323358,4,chr10,10688070,10690067,chr10_10042771_10043156;chr10_10407868_10409865,chr10_10042771_10043156,chr10_10407868_10409865,...,NaN,NaN,NaN,Yes,Gm10828,ENSMUSG00000075319,distal_proximal,5,3,5_3

In [24]:
conn_mm10.columns

Index(['peak1_chr_mm10', 'peak1_start_mm10', 'peak1_end_mm10', 'idx',
       'peak2_chr_mm10', 'peak2_start_mm10', 'peak2_end_mm10', 'connection',
       'Peak1', 'Peak2', 'coaccess', 'peak1.isproximal', 'peak1.tss.gene_name',
       'peak1.tss.gene_id', 'peak2.isproximal', 'peak2.tss.gene_name',
       'peak2.tss.gene_id', 'conn_type', 'cluster', 'subset_cluster',
       'subcluster'],
      dtype='object')

In [25]:
conn_mm10.drop(['idx'], axis=1).to_csv(
    os.path.join(dirc, 'master_cicero_conns_allneurons_distalToProximal_mm10.txt'), 
    sep='\t', header=True, index=False
)

### generate two formats
- unique CICERO regions.bed
- enhancer-gene links

In [29]:
enh_gene_links = pd.concat([
    conn_mm10[conn_mm10['peak2.isproximal'].isnull()][
        ['peak2_chr_mm10', 'peak2_start_mm10', 'peak2_end_mm10', 'peak1.tss.gene_id', 'peak1.tss.gene_name', 'coaccess']].rename(
        columns={'peak2_chr_mm10': 'chrom', 
                 'peak2_start_mm10': 'start', 
                 'peak2_end_mm10': 'end', 
                 'peak1.tss.gene_id': 'gene_id', 
                 'peak1.tss.gene_name': 'gene_name', 
                }
    ),
    conn_mm10[conn_mm10['peak1.isproximal'].isnull()][
        ['peak1_chr_mm10', 'peak1_start_mm10', 'peak1_end_mm10', 'peak2.tss.gene_id', 'peak2.tss.gene_name', 'coaccess']].rename(
        columns={'peak1_chr_mm10': 'chrom', 
                 'peak1_start_mm10': 'start', 
                 'peak1_end_mm10': 'end', 
                 'peak2.tss.gene_id': 'gene_id', 
                 'peak2.tss.gene_name': 'gene_name', 
                }
    ),
    ])

print(enh_gene_links.shape)
enh_gene_links.head()

(828128, 6)

    chrom      start        end             gene_id gene_name  coaccess
7   chr10   10319978   10321950  ENSMUSG00000075319   Gm10828  0.360986
8   chr10   10322973   10323358  ENSMUSG00000075319   Gm10828  0.218072
11  chr10  106867672  106868146  ENSMUSG00000019906     Lin7a  0.211739
12  chr10  106938270  106939438  ENSMUSG00000019906     Lin7a  0.288809
13  chr10  107289141  107290250  ENSMUSG00000019906     Lin7a  0.305184

In [30]:
# uniq enh regions
uniq_regions = enh_gene_links[['chrom', 'start', 'end']].drop_duplicates()
print(uniq_regions.shape)
uniq_regions.head()

(97430, 3)

    chrom      start        end
7   chr10   10319978   10321950
8   chr10   10322973   10323358
11  chr10  106867672  106868146
12  chr10  106938270  106939438
13  chr10  107289141  107290250

In [31]:
# save both
enh_gene_links.to_csv(os.path.join(dirc, 'master_cicero_conns_allneurons_EnhToGene_mm10.txt'), 
                   sep='\t', 
                   header=True, index=False,
                  )

uniq_regions.to_csv(os.path.join(dirc, 'master_cicero_conns_allneurons_uniq_enhs_mm10.bed'), 
                    sep='\t',
                    header=False, index=False,
                   )

### Overlap uniq regions with enhancer lists